const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const sql = fs.readFileSync(path.join(root, "supabase", "normalized-schedule-atomic-write.sql"), "utf8");
const edge = fs.readFileSync(path.join(root, "supabase", "functions", "shift-bay-api", "index.ts"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");

assert.match(sql, /create or replace function public\.write_normalized_schedule_atomically/i);
assert.match(sql, /security definer/i);
assert.match(sql, /for update/i);
assert.match(sql, /pg_try_advisory_xact_lock/i);
assert.match(sql, /set local lock_timeout = '3s'/i);
assert.match(sql, /set local statement_timeout = '20s'/i);
assert.match(sql, /shifts_location_schedule_week_idx/i);
assert.match(sql, /template_shifts_template_idx/i);
assert.match(sql, /Normalized schedule revision conflict/i);
assert.match(sql, /'code', '55P03'/i);
assert.match(sql, /'code', '40001'/i);
assert.match(sql, /'currentRevision', v_current_revision/i);
assert.match(sql, /insert into public\.shifts/i);
assert.match(sql, /insert into public\.request_offs/i);
assert.match(sql, /insert into public\.schedule_blocks/i);
assert.match(sql, /insert into public\.templates/i);
assert.match(sql, /insert into public\.template_shifts/i);
assert.match(sql, /delete from public\.shifts existing/i);
assert.match(sql, /revoke all on function public\.write_normalized_schedule_atomically/i);
assert.match(sql, /grant execute on function public\.write_normalized_schedule_atomically[\s\S]*service_role/i);
assert.match(edge, /async function writeNormalizedScheduleAtomically/);
assert.match(edge, /\/rpc\/write_normalized_schedule_atomically/);
assert.match(edge, /function normalizedAtomicCanaryEnabled\(\)/);
assert.match(edge, /NORMALIZED_ATOMIC_CONFLICT_CACHE_MS = 30_000/);
assert.match(edge, /function cachedNormalizedAtomicConflict\(/);
assert.match(edge, /function rememberNormalizedAtomicConflict\(/);
assert.match(edge, /const cachedConflict = cachedNormalizedAtomicConflict\(/);
assert.match(edge, /rememberNormalizedAtomicConflict\(/);
assert.match(edge, /normalizedAtomicConflictCache\.delete\(locationId\)/);
assert.match(edge, /Atomic Sandbox schedule writes are temporarily paused/);
assert.match(edge, /saveMode === "normalized-sandbox-atomic-revision"/);
assert.match(edge, /function normalizedAtomicScheduleState/);
assert.match(edge, /normalizedAtomicScheduleState\(state\)/);
assert.match(edge, /normalizedAtomicWrite\?\.ok === false/);
assert.match(edge, /resultCode === "55P03"/);
assert.match(edge, /resultCode === "40001"/);
assert.match(edge, /new AbortController\(\)/);
assert.match(edge, /Another Atomic Sandbox save is already in progress/);
assert.match(app, /function flushServerSaveOnClose\(\)[\s\S]*?NORMALIZED_SCHEDULE_DIRECT_WRITE_MODE\) return/);
assert.match(edge, /statement timeout|canceling statement due to lock timeout/i);
assert.match(edge, /Atomic normalized schedule writes are limited to the Sandbox location/);
assert.doesNotMatch(edge, /normalized-production-direct/);

console.log("normalized schedule atomic write migration tests passed");
